import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  layout("routes/app-layout.tsx", [
    route("dashboard", "routes/dashboard.tsx"),
    route("leaderboard", "routes/leaderboard.tsx"),
    route("profile", "routes/profile.tsx"),
    route("shop", "routes/shop.tsx"),
    route("templates", "routes/templates.tsx"),
    route("customers", "routes/customers._index.tsx"),
    route("customers/dashboard", "routes/customers.dashboard.tsx"),
    route("customers/new", "routes/customers.new.tsx"),
    route("customers/:id", "routes/customers.$id.tsx"),
    route("customers/:id/edit", "routes/customers.$id.edit.tsx"),
    route("tasks/:taskId", "routes/tasks.$taskId.tsx"),
    route("tasks/:taskId/proxy", "routes/tasks.$taskId.proxy.tsx"),
    layout("routes/admin-layout.tsx", [
      route("admin", "routes/admin._index.tsx"),
      route("admin/teams", "routes/admin.teams.tsx"),
      route("admin/zones", "routes/admin.zones.tsx"),
      route("admin/regions", "routes/admin.regions.tsx"),
      route("admin/users", "routes/admin.users.tsx"),
      route("admin/telegram", "routes/admin.telegram.tsx"),
      route("admin/cosmetics", "routes/admin.cosmetics._index.tsx"),
      route("admin/cosmetics/new", "routes/admin.cosmetics.new.tsx"),
      route("admin/cosmetics/:id", "routes/admin.cosmetics.$id.tsx"),
    ]),
  ]),
  route("api/auth/dev-login", "routes/api.auth.dev-login.tsx"),
  route("api/auth/logout", "routes/api.auth.logout.tsx"),
  route("api/auth/telegram", "routes/api.auth.telegram.tsx"),
  route("api/auth/telegram/callback", "routes/api.auth.telegram.callback.tsx"),
  route("api/cosmetics/shop", "routes/api.cosmetics.shop.tsx"),
  route("api/cosmetics/equip", "routes/api.cosmetics.equip.tsx"),
  route("api/cosmetics/inventory", "routes/api.cosmetics.inventory.tsx"),
  route("api/cosmetics/purchase", "routes/api.cosmetics.purchase.tsx"),
  route("api/push/test", "routes/api.push.test.tsx"),
  route("api/push/subscribe", "routes/api.push.subscribe.tsx"),
  route("api/push/unsubscribe", "routes/api.push.unsubscribe.tsx"),
  route("api/telegram/webhook", "routes/api.telegram.webhook.tsx"),
  route("api/jobs/reminders", "routes/api.jobs.reminders.tsx"),
  route("api/jobs/customer-reminders", "routes/api.jobs.customer-reminders.tsx"),
  route("api/jobs/monthly-reminders", "routes/api.jobs.monthly-reminders.tsx"),
  route("api/session/refresh", "routes/api.session.refresh.tsx"),
] satisfies RouteConfig;
